export const SET_ALBUM_JUMBOTRON = 'SET_ALBUM_JUMBOTRON';
export const SET_ALBUMS = 'SET_ALBUMS';
export const SET_GENRES = 'SET_GENRES';
export const FETCH_ALL_REVIEWS = 'FETCH_REVIEWS';
export const SET_REVIEWS = 'SET_REVIEWS';
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
